import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
import { Toaster } from "sonner";
import { AuthProvider } from "@/components/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ClientLayout>
            {children}
            <Toaster richColors position="top-center" />
          </ClientLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
